force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/CGPA__c.field-meta.xml
<CustomField>
    <fullName>CGPA__c</fullName>
    <label>CGPA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Application__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Jobs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Allowed_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Backlogs__c</fullName>
    <label>Allowed Backlogs</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Eligible_Branches__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Branches__c</fullName>
    <label>Eligible Branches</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Minimum_CGPA__c.field-meta.xml
<CustomField>
    <fullName>Minimum_CGPA__c</fullName>
    <label>Minimum CGPA</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OfferPostProcessingJobTest.cls
@isTest
public class OfferPostProcessingJobTest {

    @isTest
    static void testQueueableJob() {

        // Create Student
        Student__c stu = new Student__c(
            Name = 'Rahul',
            CGPA__c = 8.5,
            Active_Backlogs__c = 0,
            Branch__c = 'CSE'
        );
        insert stu;

        // Create Job
        Job__c job = new Job__c(
            Name = 'TCS',
            Minimum_CGPA__c = 7.5,
            Allowed_Backlogs__c = 0,
            Eligible_Branches__c = 'CSE'
        );
        insert job;

        // Create Application
        Application__c app = new Application__c(
            Student__c = stu.Id,
            Job__c = job.Id,
            Status__c = 'Applied'
        );
        insert app;

        Test.startTest();

        System.enqueueJob(new OfferPostProcessingJob(app.Id));

        Test.stopTest();

        // Verify record exists
        Application__c result = [
            SELECT Status__c
            FROM Application__c
            WHERE Id = :app.Id
        ];

        System.assertNotEquals(null, result);
        System.assertEquals('Selected', result.Status__c);
    }
}